CREATE DATABASE ProjectLibraryDB
GO
USE ProjectLibraryDB
GO

CREATE TABLE BookList(
BookID INT IDENTITY(1,1) CONSTRAINT pk_bookid PRIMARY KEY,
BookName VARCHAR(50) NOT NULL,
Author VARCHAR(100) NOT NULL,
YearOfPublication INT NOT NULL,
TotalQuantity INT NOT NULL,
AvailableQuantity INT NOT NULL)
GO

CREATE TABLE Members(
MemberId INT IDENTITY(1,1) CONSTRAINT pk_memberid PRIMARY KEY,
MemberName VARCHAR(20) NOT NULL,
Phone VARCHAR(10) NOT NULL,
[Address] VARCHAR(100) NOT NULL,
MemberSince DATETIME NOT NULL)
GO

CREATE TABLE LendingLog(
TransactId INT IDENTITY(1,1) CONSTRAINT pk_TransactId PRIMARY KEY,
MemberId INT FOREIGN KEY REFERENCES Members(MemberId),
BookId INT FOREIGN KEY REFERENCES BookList(BookId),
BorrowedOn DATETIME NOT NULL,
ReturnedOn DATETIME)
GO